import type { Handler, HandlerEvent } from '@netlify/functions';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';

type Arg=string|number|bigint|boolean|null|ArrayBuffer|Uint8Array;
const now=()=>new Date().toISOString();
const rid=(p='rf')=>`${p}_${crypto.randomBytes(10).toString('hex')}`;
const header=(e:HandlerEvent,n:string)=>e.headers?.[n.toLowerCase()]||e.headers?.[n]||'';
const body=(e:HandlerEvent):any=>{try{return e.body?JSON.parse(e.body):{}}catch{return {}}};
const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
const bearer=(e:HandlerEvent)=>{const h=header(e,'authorization');return h.startsWith('Bearer ')?h.slice(7):''};
const json=(x:any,status=200)=>({statusCode:status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Client, X-Device-Id, X-Device-Name, X-Device-Platform, X-App-Version','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS'},body:JSON.stringify(x)});
function enc(v:Arg){if(v===null||v===undefined)return{type:'null'};if(v instanceof ArrayBuffer||v instanceof Uint8Array)return{type:'blob',base64:Buffer.from(v instanceof Uint8Array?v:new Uint8Array(v)).toString('base64')};if(typeof v==='boolean')return{type:'integer',value:v?'1':'0'};if(typeof v==='bigint')return{type:'integer',value:v.toString()};if(typeof v==='number')return Number.isInteger(v)?{type:'integer',value:String(v)}:{type:'float',value:String(v)};return{type:'text',value:String(v)}}
class DB{endpoint:string;token:string;constructor(){let u=(process.env.TURSO_DATABASE_URL||process.env.DATABASE_URL||'libsql://rehaflow-echomedtechnologies.aws-ap-south-1.turso.io').trim().replace(/^\"|\"$/g,'').split('?')[0].replace(/\/+$/,'');if(u.startsWith('libsql://'))u=u.replace(/^libsql:\/\//,'https://');this.endpoint=`${u}/v2/pipeline`;this.token=(process.env.TURSO_AUTH_TOKEN||'').trim();if(!this.token)throw new Error('TURSO_AUTH_TOKEN is not configured in Netlify.')}
async exec(sql:string,args:Arg[]=[]){const r=await fetch(this.endpoint,{method:'POST',headers:{Authorization:`Bearer ${this.token}`,'Content-Type':'application/json'},body:JSON.stringify({requests:[{type:'execute',stmt:{sql,...(args.length?{args:args.map(enc)}:{})}},{type:'close'}]})});const p:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Turso HTTP ${r.status}: ${p?.error?.message||p?.message||r.statusText}`);for(const i of p.results||[])if(i?.type==='error')throw new Error(`Turso SQL error: ${i.error?.message||i.error}`);const z:any=(p.results||[]).find((i:any)=>i?.response?.type==='execute')?.response?.result||{};const cols=z.cols||z.columns||[];const rows=(z.rows||[]).map((rr:any[])=>{const o:any={};cols.forEach((c:any,i:number)=>{const n=typeof c==='string'?c:c.name;const v=rr[i];o[n]=v&&typeof v==='object'&&'value'in v?v:v&&typeof v==='object'&&'base64'in v?Buffer.from(v.base64,'base64'):v});return o});return{rows,cols,affectedRows:Number(z.affected_row_count||0)}}}
let client:DB|null=null;const db=()=>client||(client=new DB());
const perms:Record<string,string[]>={admin:['*'],manager:['dashboard','patients','archive','reception','beds','tasks','orders','documents','staff','analytics'],doctor:['dashboard','patients','archive','reception','beds','tasks','orders','documents'],nurse:['dashboard','patients','archive','beds','tasks','orders','documents'],registrar:['dashboard','patients','archive','reception']};
const can=(u:any,p:string)=>{const a=perms[u?.role]||[];return a.includes('*')||a.includes(p)};const forbid=()=>Object.assign(new Error('Forbidden'),{status:403});
async function audit(u:any,a:string,e:string,i:string,d:any={}){try{await db().exec(`INSERT INTO rf_audit(id,user_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?)`,[rid('audit'),u?.id||null,a,e,i,JSON.stringify(d),now()])}catch{}}
let ready=false;let preparing:Promise<void>|null=null;
async function init(){if(ready)return;if(preparing)return preparing;preparing=(async()=>{const c=db();
await c.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT,name TEXT,password_hash TEXT,role TEXT DEFAULT 'doctor',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT,access_token TEXT,refresh_token TEXT,expires_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS login_history(id TEXT PRIMARY KEY,user_id TEXT,identifier TEXT,success INTEGER,ip TEXT,user_agent TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_rooms(id TEXT PRIMARY KEY,name TEXT NOT NULL,department TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_beds(id TEXT PRIMARY KEY,room_id TEXT NOT NULL,number INTEGER NOT NULL,code TEXT UNIQUE NOT NULL,qr_payload TEXT UNIQUE NOT NULL,status TEXT DEFAULT 'available',patient_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_patients(id TEXT PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT NOT NULL,middle_name TEXT,phone TEXT,birth_date TEXT,diagnosis TEXT,status TEXT DEFAULT 'active',current_bed_id TEXT,admitted_at TEXT,discharged_at TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_bed_history(id TEXT PRIMARY KEY,patient_id TEXT,bed_id TEXT,started_at TEXT,ended_at TEXT,reason TEXT)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_tasks(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,patient_id TEXT,assigned_to TEXT,priority TEXT DEFAULT 'normal',status TEXT DEFAULT 'pending',due_at TEXT,created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_prescriptions(id TEXT PRIMARY KEY,patient_id TEXT,doctor_id TEXT,drug TEXT,dose TEXT,route TEXT,frequency TEXT,start_at TEXT,end_at TEXT,status TEXT DEFAULT 'active',note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_documents(id TEXT PRIMARY KEY,patient_id TEXT,title TEXT NOT NULL,category TEXT DEFAULT 'other',content TEXT,created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
await c.exec(`CREATE TABLE IF NOT EXISTS rf_audit(id TEXT PRIMARY KEY,user_id TEXT,action TEXT,entity TEXT,entity_id TEXT,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
for(const q of ['ALTER TABLE sessions ADD COLUMN last_seen_at TEXT','ALTER TABLE sessions ADD COLUMN device_id TEXT','ALTER TABLE sessions ADD COLUMN device_name TEXT','ALTER TABLE sessions ADD COLUMN platform TEXT','ALTER TABLE sessions ADD COLUMN app_version TEXT','ALTER TABLE sessions ADD COLUMN ip TEXT','ALTER TABLE sessions ADD COLUMN user_agent TEXT'])try{await c.exec(q)}catch{}
const adminEmail=(process.env.DEFAULT_ADMIN_EMAIL||'mishaborkovskijwork@gmail.com').trim(),adminPass=process.env.DEFAULT_ADMIN_PASSWORD||'12345678';const a=await c.exec(`SELECT id FROM users WHERE lower(email)=lower(?) LIMIT 1`,[adminEmail]);if(!a.rows.length)await c.exec(`INSERT INTO users(id,email,name,password_hash,role,active) VALUES(?,?,?,?,?,1)`,['admin-default',adminEmail,process.env.DEFAULT_ADMIN_NAME||'System Administrator',await bcrypt.hash(adminPass,10),'admin']);
const rc=await c.exec(`SELECT COUNT(*) c FROM rf_rooms`);if(!Number(rc.rows[0]?.c||0))for(const n of ['101','102','103','104','105','106','107'])await c.exec(`INSERT INTO rf_rooms(id,name,department) VALUES(?,?,?)`,[rid('room'),`Палата ${n}`,'Реабілітація']);
const bc=await c.exec(`SELECT COUNT(*) c FROM rf_beds`);if(!Number(bc.rows[0]?.c||0)){const rs=(await c.exec(`SELECT id FROM rf_rooms ORDER BY name`)).rows;for(const r of rs)for(let n=1;n<=2;n++){const code=`BED-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;await c.exec(`INSERT INTO rf_beds(id,room_id,number,code,qr_payload,status) VALUES(?,?,?,?,?,'available')`,[rid('bed'),r.id,n,code,`rehaflow://bed/${code}`])}}
ready=true})().catch(e=>{preparing=null;throw e});return preparing}
async function user(e:HandlerEvent){const t=bearer(e);if(!t)return null;const r=await db().exec(`SELECT u.id,u.email,u.name,u.role,u.active,s.id session_id,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.access_token=? LIMIT 1`,[hash(t)]);const u:any=r.rows[0];if(!u||Number(u.active??1)===0||new Date(String(u.expires_at)).getTime()<Date.now())return null;await db().exec(`UPDATE sessions SET last_seen_at=? WHERE id=?`,[now(),u.session_id]);return{id:u.id,email:u.email,name:u.name,role:u.role||'doctor',active:Number(u.active??1),sessionId:u.session_id}}
async function auth(e:HandlerEvent){const b=body(e),i=String(b.email??b.login??b.username??b.identifier??'').trim(),p=String(b.password??'');if(!i||!p)return json({error:'Email/login and password are required'},400);const r=await db().exec(`SELECT id,email,name,password_hash,role,active FROM users WHERE lower(email)=lower(?) OR lower(name)=lower(?) LIMIT 1`,[i,i]);const u:any=r.rows[0];const ok=!!u&&(String(u.password_hash||'').startsWith('$2')?await bcrypt.compare(p,String(u.password_hash)):String(u.password_hash||'')===p);await db().exec(`INSERT INTO login_history(id,user_id,identifier,success,ip,user_agent,created_at) VALUES(?,?,?,?,?,?,?)`,[rid('login'),u?.id||null,i,ok?1:0,header(e,'x-forwarded-for')||'',header(e,'user-agent')||'',now()]);if(!u||!ok||Number(u.active??0)===0)return json({error:'Invalid credentials'},401);const at=crypto.randomBytes(32).toString('hex'),rt=crypto.randomBytes(32).toString('hex'),sid=rid('sess'),exp=new Date(Date.now()+12*3600e3).toISOString();await db().exec(`INSERT INTO sessions(id,user_id,access_token,refresh_token,expires_at,last_seen_at,device_id,device_name,platform,app_version,ip,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[sid,u.id,hash(at),hash(rt),exp,now(),header(e,'x-device-id')||'web',header(e,'x-device-name')||'RehaFlow',header(e,'x-device-platform')||'web',header(e,'x-app-version')||'',header(e,'x-forwarded-for')||'',header(e,'user-agent')||'']);return json({accessToken:at,refreshToken:rt,token:at,session:{id:sid,expiresAt:exp},user:{id:u.id,email:u.email,name:u.name,role:u.role,active:Number(u.active??1)}})}
async function bind(patientId:string,bedId:string,u:any){const p=(await db().exec(`SELECT id,current_bed_id FROM rf_patients WHERE id=?`,[patientId])).rows[0],b=(await db().exec(`SELECT id,patient_id FROM rf_beds WHERE id=?`,[bedId])).rows[0];if(!p||!b)throw new Error('Patient or bed not found');if(b.patient_id&&b.patient_id!==patientId)throw new Error('Bed is already occupied');if(p.current_bed_id&&p.current_bed_id!==bedId)await release(String(p.current_bed_id),u,true);await db().exec(`UPDATE rf_beds SET patient_id=?,status='occupied',updated_at=? WHERE id=?`,[patientId,now(),bedId]);await db().exec(`UPDATE rf_patients SET current_bed_id=?,status='active',updated_at=? WHERE id=?`,[bedId,now(),patientId]);await db().exec(`INSERT INTO rf_bed_history(id,patient_id,bed_id,started_at) VALUES(?,?,?,?)`,[rid('bh'),patientId,bedId,now()]);}
async function release(bedId:string,u:any,silent=false){const b=(await db().exec(`SELECT patient_id FROM rf_beds WHERE id=?`,[bedId])).rows[0];if(!b)return;if(b.patient_id){await db().exec(`UPDATE rf_patients SET current_bed_id=NULL,updated_at=? WHERE id=?`,[now(),b.patient_id]);await db().exec(`UPDATE rf_bed_history SET ended_at=? WHERE patient_id=? AND bed_id=? AND ended_at IS NULL`,[now(),b.patient_id,bedId])}await db().exec(`UPDATE rf_beds SET patient_id=NULL,status='cleaning',updated_at=? WHERE id=?`,[now(),bedId]);if(!silent)await audit(u,'release','bed',bedId,{patientId:b.patient_id})}
export const handler:Handler=async(e)=>{try{await init();if(e.httpMethod==='OPTIONS')return json({ok:true});let p=(e.path||'/').replace(/^\/.netlify\/functions\/(api|baas)/,'').replace(/^\/api\/baas/,'').replace(/^\/api/,'')||'/';if(p==='/health'&&e.httpMethod==='GET')return json({ok:true,service:'rehaflow-api',time:now()});if(p==='/auth/login'&&e.httpMethod==='POST')return auth(e);if(p==='/auth/logout'&&e.httpMethod==='POST'){const t=bearer(e);if(t)await db().exec(`DELETE FROM sessions WHERE access_token=?`,[hash(t)]);return json({ok:true})}const u=await user(e);if(!u)return json({error:'Unauthorized'},401);if(p==='/auth/me')return json({user:u});
if(p==='/dashboard') {const a=await db().exec(`SELECT COUNT(*) c FROM rf_patients WHERE status='active'`),b=await db().exec(`SELECT status,COUNT(*) c FROM rf_beds GROUP BY status`),t=await db().exec(`SELECT COUNT(*) c FROM rf_tasks WHERE status NOT IN ('done','cancelled')`),s=await db().exec(`SELECT COUNT(*) c FROM sessions WHERE datetime(expires_at)>datetime('now') AND datetime(COALESCE(last_seen_at,created_at))>datetime('now','-15 minutes')`);const m:any={};b.rows.forEach(x=>m[x.status]=Number(x.c||0));return json({stats:{patients:Number(a.rows[0]?.c||0),occupiedBeds:m.occupied||0,availableBeds:m.available||0,cleaningBeds:m.cleaning||0,openTasks:Number(t.rows[0]?.c||0),staffOnline:Number(s.rows[0]?.c||0)}})}
if(p==='/patients'&&e.httpMethod==='GET'){const st=String(e.queryStringParameters?.status||'active'),q=String(e.queryStringParameters?.q||'');const args:any[]=[st];let sql=`SELECT p.*,b.number bed_number,b.code bed_code,r.name room_name FROM rf_patients p LEFT JOIN rf_beds b ON b.id=p.current_bed_id LEFT JOIN rf_rooms r ON r.id=b.room_id WHERE p.status=?`;if(q){const x=`%${q}%`;sql+=` AND (lower(p.first_name) LIKE lower(?) OR lower(p.last_name) LIKE lower(?) OR lower(coalesce(p.phone,'')) LIKE lower(?) OR lower(coalesce(p.diagnosis,'')) LIKE lower(?))`;args.push(x,x,x,x)}sql+=' ORDER BY p.updated_at DESC LIMIT 1000';return json({patients:(await db().exec(sql,args)).rows})}
if(p==='/patients/archive')return json({patients:(await db().exec(`SELECT * FROM rf_patients WHERE status='archived' ORDER BY discharged_at DESC`)).rows});
if(p==='/patients/history')return json({history:(await db().exec(`SELECT h.*,p.first_name,p.last_name,b.number bed_number,r.name room_name FROM rf_bed_history h LEFT JOIN rf_patients p ON p.id=h.patient_id LEFT JOIN rf_beds b ON b.id=h.bed_id LEFT JOIN rf_rooms r ON r.id=b.room_id ORDER BY h.started_at DESC LIMIT 1000`)).rows});
if(p==='/patients'&&e.httpMethod==='POST'){if(!can(u,'reception'))throw forbid();const b=body(e),pid=rid('pt');await db().exec(`INSERT INTO rf_patients(id,first_name,last_name,middle_name,phone,birth_date,diagnosis,status,admitted_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'active',?,?,?)`,[pid,b.firstName||'',b.lastName||'',b.middleName||'',b.phone||'',b.birthDate||'',b.diagnosis||'',now(),now(),now()]);if(b.bedId)await bind(pid,String(b.bedId),u);await audit(u,'create','patient',pid,b);return json({id:pid})}
const pm=p.match(/^\/patients\/([^/]+)$/);if(pm&&e.httpMethod==='PATCH'){if(!can(u,'patients'))throw forbid();const b=body(e);await db().exec(`UPDATE rf_patients SET first_name=?,last_name=?,middle_name=?,phone=?,birth_date=?,diagnosis=?,notes=?,updated_at=? WHERE id=?`,[b.firstName||'',b.lastName||'',b.middleName||'',b.phone||'',b.birthDate||'',b.diagnosis||'',b.notes||'',now(),pm[1]]);return json({ok:true})}if(pm&&e.httpMethod==='DELETE'){if(!can(u,'patients'))throw forbid();const b=(await db().exec(`SELECT current_bed_id FROM rf_patients WHERE id=?`,[pm[1]])).rows[0]?.current_bed_id;await db().exec(`UPDATE rf_patients SET status='archived',discharged_at=?,updated_at=? WHERE id=?`,[now(),now(),pm[1]]);if(b)await release(String(b),u);return json({ok:true})}
if(p==='/rooms'&&e.httpMethod==='GET')return json({rooms:(await db().exec(`SELECT r.*,COUNT(b.id) bed_count,SUM(CASE WHEN b.status='occupied' THEN 1 ELSE 0 END) occupied_count FROM rf_rooms r LEFT JOIN rf_beds b ON b.room_id=r.id GROUP BY r.id ORDER BY r.name`)).rows});if(p==='/rooms'&&e.httpMethod==='POST'){if(!can(u,'beds'))throw forbid();const b=body(e),x=rid('room');await db().exec(`INSERT INTO rf_rooms(id,name,department) VALUES(?,?,?)`,[x,b.name,b.department||'']);return json({id:x})}
if(p==='/beds'&&e.httpMethod==='GET')return json({beds:(await db().exec(`SELECT b.*,r.name room_name,r.department,p.first_name,p.last_name FROM rf_beds b LEFT JOIN rf_rooms r ON r.id=b.room_id LEFT JOIN rf_patients p ON p.id=b.patient_id ORDER BY r.name,b.number`)).rows});if(p==='/beds'&&e.httpMethod==='POST'){if(!can(u,'beds'))throw forbid();const b=body(e),x=rid('bed'),code=`BED-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;await db().exec(`INSERT INTO rf_beds(id,room_id,number,code,qr_payload,status) VALUES(?,?,?,?,?,'available')`,[x,b.roomId,b.number,code,`rehaflow://bed/${code}`]);return json({id:x,code})}
const bm=p.match(/^\/beds\/([^/]+)(?:\/(assign|release))?$/);if(bm){const bid=bm[1],act=bm[2];if(!can(u,'beds'))throw forbid();if(act==='assign'&&e.httpMethod==='POST'){await bind(String(body(e).patientId),bid,u);return json({ok:true})}if(act==='release'&&e.httpMethod==='POST'){await release(bid,u);return json({ok:true})}if(e.httpMethod==='PATCH'){const b=body(e);if(b.patientId)await bind(String(b.patientId),bid,u);if(b.status)await db().exec(`UPDATE rf_beds SET status=?,updated_at=? WHERE id=?`,[b.status,now(),bid]);return json({ok:true})}}
if(p==='/tasks'&&e.httpMethod==='GET')return json({tasks:(await db().exec(`SELECT t.*,u.name assignee_name,p.first_name,p.last_name FROM rf_tasks t LEFT JOIN users u ON u.id=t.assigned_to LEFT JOIN rf_patients p ON p.id=t.patient_id ORDER BY CASE t.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,t.created_at DESC LIMIT 1000`)).rows});if(p==='/tasks'&&e.httpMethod==='POST'){if(!can(u,'tasks'))throw forbid();const b=body(e),x=rid('task');await db().exec(`INSERT INTO rf_tasks(id,title,description,patient_id,assigned_to,priority,status,due_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[x,b.title,b.description||'',b.patientId||null,b.assignedTo||null,b.priority||'normal',b.status||'pending',b.dueAt||null,u.id,now(),now()]);return json({id:x})}const tm=p.match(/^\/tasks\/([^/]+)$/);if(tm&&e.httpMethod==='PATCH'){const b=body(e);await db().exec(`UPDATE rf_tasks SET title=?,description=?,patient_id=?,assigned_to=?,priority=?,status=?,due_at=?,updated_at=? WHERE id=?`,[b.title,b.description||'',b.patientId||null,b.assignedTo||null,b.priority||'normal',b.status||'pending',b.dueAt||null,now(),tm[1]]);return json({ok:true})}if(tm&&e.httpMethod==='DELETE'){await db().exec(`DELETE FROM rf_tasks WHERE id=?`,[tm[1]]);return json({ok:true})}
if(p==='/prescriptions'&&e.httpMethod==='GET')return json({prescriptions:(await db().exec(`SELECT x.*,p.first_name,p.last_name,u.name doctor_name FROM rf_prescriptions x LEFT JOIN rf_patients p ON p.id=x.patient_id LEFT JOIN users u ON u.id=x.doctor_id ORDER BY x.created_at DESC`)).rows});if(p==='/prescriptions'&&e.httpMethod==='POST'){if(!can(u,'orders'))throw forbid();const b=body(e),x=rid('rx');await db().exec(`INSERT INTO rf_prescriptions(id,patient_id,doctor_id,drug,dose,route,frequency,start_at,end_at,status,note,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[x,b.patientId,u.id,b.drug,b.dose||'',b.route||'',b.frequency||'',b.startAt||null,b.endAt||null,b.status||'active',b.note||'',now()]);return json({id:x})}
if(p==='/documents'&&e.httpMethod==='GET'){const pid=e.queryStringParameters?.patientId;return json({documents:(await db().exec(pid?`SELECT * FROM rf_documents WHERE patient_id=? ORDER BY created_at DESC`:`SELECT d.*,p.first_name,p.last_name FROM rf_documents d LEFT JOIN rf_patients p ON p.id=d.patient_id ORDER BY d.created_at DESC LIMIT 1000`,pid?[pid]:[])).rows})}if(p==='/documents'&&e.httpMethod==='POST'){if(!can(u,'documents'))throw forbid();const b=body(e),x=rid('doc');await db().exec(`INSERT INTO rf_documents(id,patient_id,title,category,content,created_by,created_at) VALUES(?,?,?,?,?,?,?)`,[x,b.patientId||null,b.title,b.category||'other',b.content||'',u.id,now()]);return json({id:x})}
if(p==='/users'&&e.httpMethod==='GET'){if(!can(u,'staff'))throw forbid();return json({users:(await db().exec(`SELECT id,email,name,role,active,created_at FROM users ORDER BY name`)).rows})}if(p==='/users'&&e.httpMethod==='POST'){if(!can(u,'staff'))throw forbid();const b=body(e),x=rid('usr');if(!b.email||!b.password||!b.role)return json({error:'Email, password and role are required'},400);await db().exec(`INSERT INTO users(id,email,name,password_hash,role,active) VALUES(?,?,?,?,?,?)`,[x,b.email,b.name||'',await bcrypt.hash(b.password,10),b.role,Number(b.active??1)]);return json({id:x})}const um=p.match(/^\/users\/([^/]+)$/);if(um&&e.httpMethod==='PATCH'){if(!can(u,'staff'))throw forbid();const b=body(e);let sql=`UPDATE users SET email=?,name=?,role=?,active=?`,a:any[]=[b.email,b.name||'',b.role,Number(b.active??1)];if(b.password){sql+=`,password_hash=?`;a.push(await bcrypt.hash(b.password,10))}sql+=' WHERE id=?';a.push(um[1]);await db().exec(sql,a);return json({ok:true})}if(um&&e.httpMethod==='DELETE'){if(!can(u,'staff'))throw forbid();await db().exec(`UPDATE users SET active=0 WHERE id=?`,[um[1]]);return json({ok:true})}
if(p==='/roles'&&e.httpMethod==='GET')return json({roles:Object.keys(perms).map(r=>({role:r,permissions:perms[r]}))});if(p==='/admin/sessions'&&e.httpMethod==='GET'){if(!can(u,'staff'))throw forbid();return json({sessions:(await db().exec(`SELECT s.id,s.created_at,s.last_seen_at,s.expires_at,s.device_id,s.device_name,s.platform,s.app_version,s.ip,u.name user_name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE datetime(s.expires_at)>datetime('now') ORDER BY datetime(COALESCE(s.last_seen_at,s.created_at)) DESC`)).rows})}const sm=p.match(/^\/admin\/sessions\/([^/]+)$/);if(sm&&e.httpMethod==='DELETE'){if(!can(u,'staff'))throw forbid();await db().exec(`DELETE FROM sessions WHERE id=?`,[sm[1]]);return json({ok:true})}if(p==='/audit'&&e.httpMethod==='GET'){if(!can(u,'staff'))throw forbid();return json({audit:(await db().exec(`SELECT a.*,u.name user_name FROM rf_audit a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 1000`)).rows})}
return json({error:'API endpoint not found',path:p},404)}catch(err:any){console.error(err);return json({error:err?.message||String(err)},Number(err?.status)||500)}};
