import type { Handler, HandlerEvent } from '@netlify/functions';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';

type Arg = string | number | null;
type Row = Record<string, any>;
const DEFAULT_DB = 'libsql://rehaflow-echomedtechnologies.aws-ap-south-1.turso.io';
const id = (p:string) => `${p}_${crypto.randomBytes(9).toString('hex')}`;
const now = () => new Date().toISOString();
const token = () => crypto.randomBytes(32).toString('hex');
const sha = (s:string) => crypto.createHash('sha256').update(s).digest('hex');

function cfg(){
  const raw=(process.env.TURSO_DATABASE_URL||process.env.DATABASE_URL||DEFAULT_DB).trim().replace(/^\"|\"$/g,'');
  const auth=(process.env.TURSO_AUTH_TOKEN||'').trim();
  if(!auth) throw new Error('TURSO_AUTH_TOKEN is not configured in Netlify.');
  const base=raw.replace(/^libsql:\/\//,'https://').replace(/\/+$/,'');
  return {endpoint:`${base}/v2/pipeline`,auth};
}
function enc(v:Arg){if(v===null||v===undefined)return{type:'null'};if(typeof v==='number')return Number.isInteger(v)?{type:'integer',value:String(v)}:{type:'float',value:String(v)};return{type:'text',value:String(v)};}
class DB{
  private endpoint:string; private auth:string;
  constructor(){const c=cfg();this.endpoint=c.endpoint;this.auth=c.auth;}
  async q(sql:string,args:Arg[]=[]):Promise<{rows:Row[],affected:number}>{
    const r=await fetch(this.endpoint,{method:'POST',headers:{Authorization:`Bearer ${this.auth}`,'Content-Type':'application/json'},body:JSON.stringify({requests:[{type:'execute',stmt:{sql,...(args.length?{args:args.map(enc)}:{})}},{type:'close'}]})});
    const p:any=await r.json().catch(()=>({}));
    if(!r.ok)throw new Error(`Turso HTTP ${r.status}: ${p?.error?.message||p?.message||r.statusText}`);
    const out=p.results?.find((x:any)=>x?.response?.type==='execute')?.response?.result||{};
    const cols=out.cols||out.columns||[];const rows=(out.rows||[]).map((rr:any[])=>{const o:Row={};cols.forEach((c:any,i:number)=>{const n=typeof c==='string'?c:c.name;const v=rr[i];o[n]=v&&typeof v==='object'&&'value'in v?v.value:v&&typeof v==='object'&&'base64'in v?Buffer.from(v.base64,'base64'):v});return o});
    return{rows,affected:Number(out.affected_row_count||0)};
  }
}
let database:DB|null=null;let boot:Promise<void>|null=null;let ready=false;const db=()=>database||(database=new DB());
const json=(body:any,status=200)=>({statusCode:status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,Authorization,X-Client,X-Device-Id,X-Device-Name,X-Device-Platform,X-App-Version','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS'},body:JSON.stringify(body)});
const body=(e:HandlerEvent)=>{try{return e.body?JSON.parse(e.body):{}}catch{return{}}};
const query=(e:HandlerEvent,k:string,d='')=>e.queryStringParameters?.[k]??d;
const bearer=(e:HandlerEvent)=>{const h=e.headers?.authorization||e.headers?.Authorization||'';return h.startsWith('Bearer ')?h.slice(7):''};
const PERMS:Record<string,string[]>={admin:['*'],manager:['dashboard','patients','archive','reception','beds','tasks','orders','documents','staff','analytics'],doctor:['dashboard','patients','archive','reception','beds','tasks','orders','documents'],nurse:['dashboard','patients','archive','beds','tasks','orders','documents'],registrar:['dashboard','patients','archive','reception']};
const can=(u:any,p:string)=>PERMS[u?.role]?.includes('*')||PERMS[u?.role]?.includes(p);
const forbidden=()=>Object.assign(new Error('Forbidden'),{status:403});
const unauthorized=()=>Object.assign(new Error('Unauthorized'),{status:401});

async function init(){
  if(ready)return;if(boot)return boot;
  boot=(async()=>{
    const d=db();
    const ddl=[
      `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,password_hash TEXT,role TEXT DEFAULT 'doctor',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY,user_id TEXT,access_token TEXT,refresh_token TEXT,expires_at TEXT,device_id TEXT,device_name TEXT,platform TEXT,app_version TEXT,last_seen_at TEXT,ip TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS login_history (id TEXT PRIMARY KEY,user_id TEXT,identifier TEXT,success INTEGER,ip TEXT,user_agent TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS rooms (id TEXT PRIMARY KEY,name TEXT NOT NULL,department TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS beds (id TEXT PRIMARY KEY,room_id TEXT NOT NULL,number INTEGER NOT NULL,code TEXT UNIQUE NOT NULL,status TEXT DEFAULT 'available',patient_id TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS bed_history (id TEXT PRIMARY KEY,bed_id TEXT,patient_id TEXT,started_at TEXT,ended_at TEXT)`,
      `CREATE TABLE IF NOT EXISTS patients (id TEXT PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT NOT NULL,middle_name TEXT,birth_date TEXT,sex TEXT,phone TEXT,email TEXT,address TEXT,passport_id TEXT,insurance_number TEXT,emergency_name TEXT,emergency_phone TEXT,blood_type TEXT,allergies TEXT,diagnosis TEXT,admission_reason TEXT,department TEXT,attending_doctor_id TEXT,room_id TEXT,bed_id TEXT,status TEXT DEFAULT 'active',admitted_at TEXT DEFAULT CURRENT_TIMESTAMP,discharged_at TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,patient_id TEXT,assigned_to TEXT,priority TEXT DEFAULT 'normal',status TEXT DEFAULT 'pending',due_at TEXT,created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS prescriptions (id TEXT PRIMARY KEY,patient_id TEXT,doctor_id TEXT,drug TEXT NOT NULL,dose TEXT,route TEXT,frequency TEXT,note TEXT,status TEXT DEFAULT 'active',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY,patient_id TEXT,title TEXT NOT NULL,category TEXT DEFAULT 'other',content TEXT,file_name TEXT,file_url TEXT,created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY,user_id TEXT,action TEXT,entity TEXT,entity_id TEXT,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`
    ];
    for(const x of ddl)await d.q(x);
    const email=process.env.DEFAULT_ADMIN_EMAIL?.trim()||'mishaborkovskijwork@gmail.com';const ex=await d.q('SELECT id FROM users WHERE lower(email)=lower(?) LIMIT 1',[email]);
    if(!ex.rows.length)await d.q('INSERT INTO users(id,email,name,password_hash,role,active) VALUES(?,?,?,?,?,1)',['admin-default',email,process.env.DEFAULT_ADMIN_NAME?.trim()||'System Administrator',await bcrypt.hash(process.env.DEFAULT_ADMIN_PASSWORD||'12345678',10),'admin']);
    const rc=await d.q('SELECT COUNT(*) count FROM rooms');
    if(Number(rc.rows[0]?.count||0)===0)for(let i=101;i<=103;i++)await d.q('INSERT INTO rooms(id,name,department) VALUES(?,?,?)',[id('room'),`Палата ${i}`,'Реабілітація']);
    ready=true;
  })().catch(e=>{boot=null;throw e});return boot;
}
async function currentUser(e:HandlerEvent){const t=bearer(e);if(!t)return null;const r=await db().q('SELECT u.*,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.access_token=? LIMIT 1',[sha(t)]);const u=r.rows[0];if(!u||Number(u.active)!==1||!u.expires_at||new Date(String(u.expires_at)).getTime()<Date.now())return null;await db().q('UPDATE sessions SET last_seen_at=? WHERE access_token=?',[now(),sha(t)]);return u;}
async function requireUser(e:HandlerEvent){const u=await currentUser(e);if(!u)throw unauthorized();return u;}
async function audit(u:any,action:string,entity:string,entityId:string,details:any={}){await db().q('INSERT INTO audit_log(id,user_id,action,entity,entity_id,details) VALUES(?,?,?,?,?,?)',[id('audit'),u?.id||null,action,entity,entityId,JSON.stringify(details)]);}

async function auth(path:string,e:HandlerEvent){
 if(e.httpMethod==='OPTIONS')return json({ok:true});
 if(path==='/login'&&e.httpMethod==='POST'){const b=body(e),identifier=String(b.email??b.login??b.username??b.identifier??'').trim(),password=String(b.password??'');if(!identifier||!password)return json({error:'Email/login and password are required'},400);const r=await db().q('SELECT * FROM users WHERE lower(email)=lower(?) OR lower(name)=lower(?) LIMIT 1',[identifier,identifier]);const u=r.rows[0];const ok=!!u&&(String(u.password_hash||'').startsWith('$2')?await bcrypt.compare(password,String(u.password_hash)):String(u.password_hash||'')===password);await db().q('INSERT INTO login_history(id,user_id,identifier,success,ip,user_agent) VALUES(?,?,?,?,?,?)',[id('login'),u?.id||null,identifier,ok?1:0,e.headers?.['x-forwarded-for']||null,e.headers?.['user-agent']||null]);if(!u||!ok||Number(u.active)!==1)return json({error:'Invalid credentials'},401);const at=token(),rt=token(),sid=id('sess'),expires=new Date(Date.now()+43200000).toISOString();await db().q('INSERT INTO sessions(id,user_id,access_token,refresh_token,expires_at,device_id,device_name,platform,app_version,last_seen_at,ip) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[sid,u.id,sha(at),sha(rt),expires,b.deviceId||null,b.deviceName||'RehaFlow Desktop',b.platform||'windows',b.appVersion||null,now(),e.headers?.['x-forwarded-for']||null]);return json({accessToken:at,refreshToken:rt,token:at,session:{id:sid,expiresAt:expires},user:{id:u.id,email:u.email,name:u.name,role:u.role,active:Number(u.active)}});}
 if(path==='/logout'&&e.httpMethod==='POST'){const t=bearer(e);if(t)await db().q('DELETE FROM sessions WHERE access_token=?',[sha(t)]);return json({ok:true});}
 if((path==='/me'||path==='/session')&&e.httpMethod==='GET'){const u=await currentUser(e);if(!u)return json({error:'Unauthorized'},401);return json({authenticated:true,user:{id:u.id,email:u.email,name:u.name,role:u.role,active:Number(u.active)}});}
 return json({error:'API endpoint not found'},404);
}
async function usersApi(path:string,e:HandlerEvent,u:any){
 if(path==='/staff/doctors'&&e.httpMethod==='GET'){if(!can(u,'reception')&&!can(u,'staff'))throw forbidden();const r=await db().q("SELECT id,name,email,role FROM users WHERE active=1 AND role IN ('doctor','manager','admin') ORDER BY name");return json({doctors:r.rows});}
 if(!can(u,'staff'))throw forbidden();
 if(path==='/users'&&e.httpMethod==='GET'){const x=query(e,'q');const r=await db().q("SELECT id,email,name,role,active,created_at FROM users WHERE (?='' OR lower(email) LIKE lower(?) OR lower(name) LIKE lower(?)) ORDER BY name",[x,`%${x}%`,`%${x}%`]);return json({users:r.rows});}
 if(path==='/users'&&e.httpMethod==='POST'){const b=body(e);if(!b.name||!b.email||!b.password)return json({error:'name, email and password are required'},400);const ex=await db().q('SELECT id FROM users WHERE lower(email)=lower(?)',[b.email]);if(ex.rows.length)return json({error:'Email already exists'},409);const nid=id('usr');await db().q('INSERT INTO users(id,email,name,password_hash,role,active) VALUES(?,?,?,?,?,?)',[nid,b.email,b.name,await bcrypt.hash(String(b.password),10),b.role||'doctor',b.active===false?0:1]);await audit(u,'create','user',nid,{role:b.role});return json({user:{id:nid,email:b.email,name:b.name,role:b.role||'doctor',active:b.active===false?0:1}},201);}
 const m=path.match(/^\/users\/([^/]+)$/);if(m&&e.httpMethod==='PATCH'){const b=body(e),sets:string[]=[],args:Arg[]=[];if(b.name!==undefined){sets.push('name=?');args.push(b.name)}if(b.role!==undefined){sets.push('role=?');args.push(b.role)}if(b.active!==undefined){sets.push('active=?');args.push(b.active?1:0)}if(b.password){sets.push('password_hash=?');args.push(await bcrypt.hash(String(b.password),10))}if(sets.length){args.push(m[1]);await db().q(`UPDATE users SET ${sets.join(',')} WHERE id=?`,args);await audit(u,'update','user',m[1],b)}return json({ok:true});}
 if(m&&e.httpMethod==='DELETE'){if(m[1]===u.id)return json({error:'You cannot delete your own account'},400);await db().q('DELETE FROM users WHERE id=?',[m[1]]);await audit(u,'delete','user',m[1]);return json({ok:true});}
 if(path==='/roles'&&e.httpMethod==='GET')return json({roles:Object.entries(PERMS).map(([role,permissions])=>({role,permissions}))});
 return json({error:'API endpoint not found'},404);
}
async function patientsApi(path:string,e:HandlerEvent,u:any){
 if(!can(u,'patients'))throw forbidden();
 if(path==='/patients'&&e.httpMethod==='GET'){const status=query(e,'status','active'),s=query(e,'q');const r=await db().q("SELECT p.*,u.name attending_doctor_name,r.name room_name,b.number bed_number,b.code bed_code FROM patients p LEFT JOIN users u ON u.id=p.attending_doctor_id LEFT JOIN rooms r ON r.id=p.room_id LEFT JOIN beds b ON b.id=p.bed_id WHERE (?='' OR p.status=?) AND (?='' OR lower(p.first_name||' '||p.last_name||' '||coalesce(p.phone,'')) LIKE lower(?)) ORDER BY p.last_name,p.first_name LIMIT 1000",[status,status,s,`%${s}%`]);return json({patients:r.rows,items:r.rows});}
 if(path==='/patients'&&e.httpMethod==='POST'){const b=body(e),first=b.firstName??b.first_name,last=b.lastName??b.last_name;if(!first||!last)return json({error:'First and last name are required'},400);const nid=id('pt');await db().q('INSERT INTO patients(id,first_name,last_name,middle_name,birth_date,sex,phone,email,address,passport_id,insurance_number,emergency_name,emergency_phone,blood_type,allergies,diagnosis,admission_reason,department,attending_doctor_id,room_id,bed_id,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[nid,first,last,b.middleName??null,b.birthDate??null,b.sex??null,b.phone??null,b.email??null,b.address??null,b.passportId??null,b.insuranceNumber??null,b.emergencyName??null,b.emergencyPhone??null,b.bloodType??null,b.allergies??null,b.diagnosis??null,b.admissionReason??null,b.department??null,b.attendingDoctorId??null,b.roomId??null,b.bedId??null,b.status||'active',b.notes??null]);if(b.bedId)await assignBedInternal(String(b.bedId),nid);await audit(u,'create','patient',nid,b);return json({patient:{id:nid,...b}},201);}
 const m=path.match(/^\/patients\/([^/]+)$/);if(m&&e.httpMethod==='GET'){const r=await db().q('SELECT * FROM patients WHERE id=?',[m[1]]);return r.rows[0]?json({patient:r.rows[0]}):json({error:'Patient not found'},404);}
 if(m&&(e.httpMethod==='PATCH'||e.httpMethod==='PUT')){const b=body(e),map:any={firstName:'first_name',lastName:'last_name',middleName:'middle_name',birthDate:'birth_date',sex:'sex',phone:'phone',email:'email',address:'address',passportId:'passport_id',insuranceNumber:'insurance_number',emergencyName:'emergency_name',emergencyPhone:'emergency_phone',bloodType:'blood_type',allergies:'allergies',diagnosis:'diagnosis',admissionReason:'admission_reason',department:'department',attendingDoctorId:'attending_doctor_id',roomId:'room_id',bedId:'bed_id',status:'status',notes:'notes'},sets:string[]=[],args:Arg[]=[];for(const[k,c]of Object.entries(map))if(b[k]!==undefined){sets.push(`${c}=?`);args.push(b[k])}sets.push('updated_at=?');args.push(now(),m[1]);await db().q(`UPDATE patients SET ${sets.join(',')} WHERE id=?`,args);await audit(u,'update','patient',m[1],b);return json({ok:true});}
 if(m&&e.httpMethod==='DELETE'){await db().q('DELETE FROM patients WHERE id=?',[m[1]]);await audit(u,'delete','patient',m[1]);return json({ok:true});}
 return json({error:'API endpoint not found'},404);
}
async function archiveApi(path:string,e:HandlerEvent,u:any){if(!can(u,'archive'))throw forbidden();if(path==='/archive'&&e.httpMethod==='GET'){const r=await db().q("SELECT p.*,u.name attending_doctor_name FROM patients p LEFT JOIN users u ON u.id=p.attending_doctor_id WHERE p.status='archived' OR p.discharged_at IS NOT NULL ORDER BY p.discharged_at DESC");return json({patients:r.rows});}if(path==='/patient-history'&&e.httpMethod==='GET'){const r=await db().q("SELECT h.*,p.first_name,p.last_name,r.name room_name,b.number bed_number FROM bed_history h LEFT JOIN patients p ON p.id=h.patient_id LEFT JOIN beds b ON b.id=h.bed_id LEFT JOIN rooms r ON r.id=b.room_id ORDER BY h.started_at DESC");return json({history:r.rows});}const m=path.match(/^\/patients\/([^/]+)\/archive$/);if(m&&e.httpMethod==='POST'){await db().q("UPDATE patients SET status='archived',discharged_at=?,bed_id=NULL,room_id=NULL WHERE id=?",[now(),m[1]]);await db().q("UPDATE bed_history SET ended_at=? WHERE patient_id=? AND ended_at IS NULL",[now(),m[1]]);await db().q("UPDATE beds SET patient_id=NULL,status='cleaning',updated_at=? WHERE patient_id=?",[now(),m[1]]);await audit(u,'archive','patient',m[1]);return json({ok:true});}return json({error:'API endpoint not found'},404);}
async function assignBedInternal(bedId:string,patientId:string){const b=(await db().q('SELECT * FROM beds WHERE id=?',[bedId])).rows[0];if(!b)throw new Error('Bed not found');if(b.patient_id&&b.patient_id!==patientId)throw new Error('Bed is already occupied');await db().q("UPDATE bed_history SET ended_at=? WHERE bed_id=? AND ended_at IS NULL",[now(),bedId]);await db().q('INSERT INTO bed_history(id,bed_id,patient_id,started_at) VALUES(?,?,?,?)',[id('bh'),bedId,patientId,now()]);await db().q("UPDATE beds SET patient_id=?,status='occupied',updated_at=? WHERE id=?",[patientId,now(),bedId]);await db().q('UPDATE patients SET bed_id=?,room_id=? WHERE id=?',[bedId,b.room_id,patientId]);}
async function bedsApi(path:string,e:HandlerEvent,u:any){if(!can(u,'beds'))throw forbidden();
 if(path==='/rooms'&&e.httpMethod==='GET'){const r=await db().q("SELECT r.*,COUNT(b.id) bed_count,COALESCE(SUM(CASE WHEN b.status='occupied' THEN 1 ELSE 0 END),0) occupied_count FROM rooms r LEFT JOIN beds b ON b.room_id=r.id GROUP BY r.id ORDER BY r.name");return json({rooms:r.rows});}
 if(path==='/rooms'&&e.httpMethod==='POST'){const b=body(e),nid=id('room');if(!b.name)return json({error:'name is required'},400);await db().q('INSERT INTO rooms(id,name,department) VALUES(?,?,?)',[nid,b.name,b.department||null]);await audit(u,'create','room',nid,b);return json({room:{id:nid,...b}},201);}
 if(path==='/beds'&&e.httpMethod==='GET'){const r=await db().q('SELECT b.*,r.name room_name,p.first_name,p.last_name FROM beds b JOIN rooms r ON r.id=b.room_id LEFT JOIN patients p ON p.id=b.patient_id ORDER BY r.name,b.number');return json({beds:r.rows});}
 if(path==='/beds'&&e.httpMethod==='POST'){const b=body(e),roomId=String(b.roomId||b.room_id),number=Number(b.number||1);if(!roomId)return json({error:'roomId is required'},400);const code=`RF-${roomId.slice(-6).toUpperCase()}-${String(number).padStart(2,'0')}`,nid=id('bed');const exists=await db().q('SELECT id FROM beds WHERE room_id=? AND number=?',[roomId,number]);if(exists.rows.length)return json({error:'Bed number already exists in this room'},409);await db().q('INSERT INTO beds(id,room_id,number,code,status) VALUES(?,?,?,?,?)',[nid,roomId,number,code,'available']);await audit(u,'create','bed',nid,b);return json({bed:{id:nid,room_id:roomId,number,code,status:'available'}},201);}
 const rel=path.match(/^\/beds\/([^/]+)\/release$/);if(rel&&e.httpMethod==='POST'){const b=(await db().q('SELECT patient_id FROM beds WHERE id=?',[rel[1]])).rows[0];await db().q('UPDATE bed_history SET ended_at=? WHERE bed_id=? AND ended_at IS NULL',[now(),rel[1]]);await db().q("UPDATE beds SET patient_id=NULL,status='cleaning',updated_at=? WHERE id=?",[now(),rel[1]]);if(b?.patient_id)await db().q('UPDATE patients SET bed_id=NULL,room_id=NULL WHERE id=?',[b.patient_id]);await audit(u,'release','bed',rel[1]);return json({ok:true});}
 const m=path.match(/^\/beds\/([^/]+)$/);if(m&&(e.httpMethod==='PATCH'||e.httpMethod==='PUT')){const b=body(e);if(b.patientId)await assignBedInternal(m[1],String(b.patientId));if(b.status&&b.status!=='occupied')await db().q('UPDATE beds SET status=?,updated_at=? WHERE id=?',[b.status,now(),m[1]]);await audit(u,'update','bed',m[1],b);return json({ok:true});}
 return json({error:'API endpoint not found'},404);
}
async function tasksApi(path:string,e:HandlerEvent,u:any){if(!can(u,'tasks'))throw forbidden();if(path==='/tasks'&&e.httpMethod==='GET'){const r=await db().q("SELECT t.*,p.first_name,p.last_name,u.name assignee_name FROM tasks t LEFT JOIN patients p ON p.id=t.patient_id LEFT JOIN users u ON u.id=t.assigned_to ORDER BY CASE t.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,t.created_at DESC");return json({tasks:r.rows});}if(path==='/tasks'&&e.httpMethod==='POST'){const b=body(e),nid=id('task');if(!b.title)return json({error:'title is required'},400);await db().q('INSERT INTO tasks(id,title,description,patient_id,assigned_to,priority,status,due_at,created_by) VALUES(?,?,?,?,?,?,?,?,?)',[nid,b.title,b.description||null,b.patientId||null,b.assignedTo||null,b.priority||'normal',b.status||'pending',b.dueAt||null,u.id]);return json({task:{id:nid,...b}},201);}const m=path.match(/^\/tasks\/([^/]+)$/);if(m&&(e.httpMethod==='PATCH'||e.httpMethod==='PUT')){const b=body(e),map:any={title:'title',description:'description',patientId:'patient_id',assignedTo:'assigned_to',priority:'priority',status:'status',dueAt:'due_at'},sets:string[]=[],args:Arg[]=[];for(const[k,c]of Object.entries(map))if(b[k]!==undefined){sets.push(`${c}=?`);args.push(b[k])}sets.push('updated_at=?');args.push(now(),m[1]);await db().q(`UPDATE tasks SET ${sets.join(',')} WHERE id=?`,args);return json({ok:true});}if(m&&e.httpMethod==='DELETE'){await db().q('DELETE FROM tasks WHERE id=?',[m[1]]);return json({ok:true});}return json({error:'API endpoint not found'},404);}
async function ordersApi(path:string,e:HandlerEvent,u:any){if(!can(u,'orders'))throw forbidden();if(path==='/prescriptions'&&e.httpMethod==='GET'){const r=await db().q('SELECT x.*,p.first_name,p.last_name,u.name doctor_name FROM prescriptions x LEFT JOIN patients p ON p.id=x.patient_id LEFT JOIN users u ON u.id=x.doctor_id ORDER BY x.created_at DESC');return json({prescriptions:r.rows});}if(path==='/prescriptions'&&e.httpMethod==='POST'){const b=body(e),nid=id('rx');if(!b.patientId||!b.drug)return json({error:'patientId and drug are required'},400);await db().q('INSERT INTO prescriptions(id,patient_id,doctor_id,drug,dose,route,frequency,note,status) VALUES(?,?,?,?,?,?,?,?,?)',[nid,b.patientId,u.id,b.drug,b.dose||null,b.route||null,b.frequency||null,b.note||null,'active']);return json({prescription:{id:nid,...b,doctorId:u.id}},201);}return json({error:'API endpoint not found'},404);}
async function docsApi(path:string,e:HandlerEvent,u:any){if(!can(u,'documents'))throw forbidden();if(path==='/documents'&&e.httpMethod==='GET'){const pid=query(e,'patientId');const r=await db().q('SELECT d.*,p.first_name,p.last_name,u.name created_by_name FROM documents d LEFT JOIN patients p ON p.id=d.patient_id LEFT JOIN users u ON u.id=d.created_by WHERE (?=\'\' OR d.patient_id=?) ORDER BY d.created_at DESC',[pid,pid]);return json({documents:r.rows});}if(path==='/documents'&&e.httpMethod==='POST'){const b=body(e),nid=id('doc');if(!b.title)return json({error:'title is required'},400);await db().q('INSERT INTO documents(id,patient_id,title,category,content,file_name,file_url,created_by) VALUES(?,?,?,?,?,?,?,?)',[nid,b.patientId||null,b.title,b.category||'other',b.content||null,b.fileName||null,b.fileUrl||null,u.id]);return json({document:{id:nid,...b}},201);}return json({error:'API endpoint not found'},404);}
async function sessionsApi(path:string,e:HandlerEvent,u:any){if(!can(u,'staff'))throw forbidden();if(path==='/sessions'&&e.httpMethod==='GET'){const r=await db().q("SELECT s.id,s.device_id,s.device_name,s.platform,s.app_version,s.last_seen_at,s.created_at,u.name user_name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE u.active=1 ORDER BY s.last_seen_at DESC");return json({sessions:r.rows});}const m=path.match(/^\/sessions\/([^/]+)$/);if(m&&e.httpMethod==='DELETE'){await db().q('DELETE FROM sessions WHERE id=?',[m[1]]);return json({ok:true});}return json({error:'API endpoint not found'},404);}
async function analytics(path:string,e:HandlerEvent,u:any){if(!can(u,'analytics'))throw forbidden();const p=await db().q("SELECT COUNT(*) count FROM patients WHERE status='active'"),a=await db().q("SELECT COUNT(*) count FROM patients WHERE status='archived' OR discharged_at IS NOT NULL"),b=await db().q("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN status='occupied' THEN 1 ELSE 0 END),0) occupied,COALESCE(SUM(CASE WHEN status='available' THEN 1 ELSE 0 END),0) available,COALESCE(SUM(CASE WHEN status='cleaning' THEN 1 ELSE 0 END),0) cleaning FROM beds"),t=await db().q("SELECT COUNT(*) count FROM tasks WHERE status NOT IN ('done','completed')"),s=await db().q("SELECT COUNT(DISTINCT user_id) count FROM sessions WHERE last_seen_at>=datetime('now','-15 minutes')");return json({stats:{patients:Number(p.rows[0]?.count||0),archivedPatients:Number(a.rows[0]?.count||0),occupiedBeds:Number(b.rows[0]?.occupied||0),availableBeds:Number(b.rows[0]?.available||0),cleaningBeds:Number(b.rows[0]?.cleaning||0),totalBeds:Number(b.rows[0]?.total||0),openTasks:Number(t.rows[0]?.count||0),staffOnline:Number(s.rows[0]?.count||0)}});}

export const handler:Handler=async(e)=>{try{await init();if(e.httpMethod==='OPTIONS')return json({ok:true});let path=(e.path||'').replace(/^\/.netlify\/functions\/api2/,'').replace(/^\/api\/baas/,'').replace(/^\/api/,'')||'/';if(path.startsWith('/auth/'))return auth(path.slice(5),e);const u=await requireUser(e);if(path==='/health')return json({ok:true,service:'rehaflow-api'});if(path.startsWith('/staff')||path.startsWith('/users')||path==='/roles')return usersApi(path,e,u);if(path.startsWith('/patients/')&&path.endsWith('/archive'))return archiveApi(path,e,u);if(path==='/archive'||path==='/patient-history')return archiveApi(path,e,u);if(path.startsWith('/patients'))return patientsApi(path,e,u);if(path.startsWith('/rooms')||path.startsWith('/beds'))return bedsApi(path,e,u);if(path.startsWith('/tasks'))return tasksApi(path,e,u);if(path.startsWith('/prescriptions'))return ordersApi(path,e,u);if(path.startsWith('/documents'))return docsApi(path,e,u);if(path.startsWith('/sessions'))return sessionsApi(path,e,u);if(path==='/dashboard'||path==='/analytics')return analytics(path,e,u);if(path==='/audit'&&e.httpMethod==='GET'){if(!can(u,'staff'))throw forbidden();const r=await db().q('SELECT a.*,u.name user_name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 500');return json({audit:r.rows});}if(path==='/permissions'&&e.httpMethod==='GET')return json({role:u.role,permissions:PERMS[u.role]||[]});return json({error:'API endpoint not found',path},404)}catch(err:any){console.error(err);return json({error:err?.message||String(err)},err?.status||500)}};
