import crypto from 'node:crypto';
const DEFAULT_DB='libsql://rehaflow-echomedtechnologies.aws-ap-south-1.turso.io';
const enc=(v:any)=>v===null||v===undefined?{type:'null'}:typeof v==='boolean'?{type:'integer',value:v?'1':'0'}:typeof v==='number'?(Number.isInteger(v)?{type:'integer',value:String(v)}:{type:'float',value:String(v)}):{type:'text',value:String(v)};
class DB{endpoint:string;token:string;constructor(){let u=(process.env.TURSO_DATABASE_URL||process.env.DATABASE_URL||DEFAULT_DB).trim().split('?')[0].replace(/\/+$/,'');if(u.startsWith('libsql://'))u=u.replace('libsql://','https://');this.endpoint=`${u}/v2/pipeline`;this.token=(process.env.TURSO_AUTH_TOKEN||'').trim();if(!this.token)throw new Error('TURSO_AUTH_TOKEN is not configured in Netlify.')}async q(sql:string,args:any[]=[]){const r=await fetch(this.endpoint,{method:'POST',headers:{Authorization:`Bearer ${this.token}`,'Content-Type':'application/json'},body:JSON.stringify({requests:[{type:'execute',stmt:{sql,...(args.length?{args:args.map(enc)}:{})}},{type:'close'}]})});const p:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Turso HTTP ${r.status}: ${p?.error?.message||r.statusText}`);for(const x of p.results||[])if(x?.type==='error')throw new Error(`Turso SQL error: ${x.error?.message||x.error}`);return (p.results||[]).find((x:any)=>x?.response?.type==='execute')?.response?.result||{};}}
let D:DB|null=null;const db=()=>D||(D=new DB());
async function add(t:string,c:string,typ:string){try{await db().q(`ALTER TABLE ${t} ADD COLUMN ${c} ${typ}`)}catch{}}
export async function migrate(){
 await db().q(`CREATE TABLE IF NOT EXISTS rf_rooms(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,department TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await db().q(`CREATE TABLE IF NOT EXISTS rf_beds(id TEXT PRIMARY KEY,room_id TEXT,number INTEGER,code TEXT UNIQUE,qr_payload TEXT,status TEXT DEFAULT 'available',patient_id TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await db().q(`CREATE TABLE IF NOT EXISTS rf_patients(id TEXT PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT NOT NULL,middle_name TEXT,birth_date TEXT,sex TEXT,phone TEXT,email TEXT,address TEXT,passport_id TEXT,insurance_number TEXT,emergency_name TEXT,emergency_phone TEXT,blood_type TEXT,allergies TEXT,diagnosis TEXT,admission_reason TEXT,department TEXT,attending_doctor_id TEXT,room_id TEXT,bed_id TEXT,current_bed_id TEXT,status TEXT DEFAULT 'active',notes TEXT,admitted_at TEXT,discharged_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await db().q(`CREATE TABLE IF NOT EXISTS rf_bed_history(id TEXT PRIMARY KEY,patient_id TEXT,bed_id TEXT,started_at TEXT,ended_at TEXT,reason TEXT)`);
 await db().q(`CREATE TABLE IF NOT EXISTS rf_tasks(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,patient_id TEXT,assigned_to TEXT,priority TEXT DEFAULT 'normal',status TEXT DEFAULT 'pending',due_at TEXT,created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await db().q(`CREATE TABLE IF NOT EXISTS rf_prescriptions(id TEXT PRIMARY KEY,patient_id TEXT,doctor_id TEXT,drug TEXT NOT NULL,dose TEXT,route TEXT,frequency TEXT,start_at TEXT,end_at TEXT,status TEXT DEFAULT 'active',note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await db().q(`CREATE TABLE IF NOT EXISTS rf_documents(id TEXT PRIMARY KEY,patient_id TEXT,title TEXT NOT NULL,category TEXT DEFAULT 'other',content TEXT,file_name TEXT,file_url TEXT,created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await db().q(`CREATE TABLE IF NOT EXISTS rf_audit(id TEXT PRIMARY KEY,user_id TEXT,action TEXT,entity TEXT,entity_id TEXT,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 for(const [t,c,ty] of [['rf_patients','email','TEXT'],['rf_patients','address','TEXT'],['rf_patients','passport_id','TEXT'],['rf_patients','insurance_number','TEXT'],['rf_patients','emergency_name','TEXT'],['rf_patients','emergency_phone','TEXT'],['rf_patients','blood_type','TEXT'],['rf_patients','allergies','TEXT'],['rf_patients','admission_reason','TEXT'],['rf_patients','department','TEXT'],['rf_patients','attending_doctor_id','TEXT'],['rf_patients','room_id','TEXT'],['rf_patients','bed_id','TEXT'],['rf_patients','current_bed_id','TEXT'],['rf_patients','admitted_at','TEXT'],['rf_patients','discharged_at','TEXT'],['rf_beds','room_id','TEXT'],['rf_beds','number','INTEGER'],['rf_beds','code','TEXT'],['rf_beds','qr_payload','TEXT'],['rf_beds','patient_id','TEXT'],['rf_beds','updated_at','TEXT'],['sessions','device_id','TEXT'],['sessions','device_name','TEXT'],['sessions','platform','TEXT'],['sessions','app_version','TEXT'],['sessions','last_seen_at','TEXT'],['sessions','ip','TEXT'],['sessions','user_agent','TEXT']] as const) await add(t,c,ty);
 try{await db().q(`INSERT OR IGNORE INTO rf_rooms(id,name,department,active,created_at) SELECT id,name,department,COALESCE(active,1),COALESCE(created_at,CURRENT_TIMESTAMP) FROM rooms`)}catch{}
 try{await db().q(`INSERT OR IGNORE INTO rf_patients(id,first_name,last_name,middle_name,birth_date,sex,phone,email,address,passport_id,insurance_number,emergency_name,emergency_phone,blood_type,allergies,diagnosis,admission_reason,department,attending_doctor_id,room_id,bed_id,status,admitted_at,discharged_at,notes,created_at,updated_at) SELECT id,first_name,last_name,middle_name,birth_date,sex,phone,email,address,passport_id,insurance_number,emergency_name,emergency_phone,blood_type,allergies,diagnosis,admission_reason,department,attending_doctor_id,room_id,bed_id,status,admitted_at,discharged_at,notes,created_at,updated_at FROM patients`)}catch{}
 try{await db().q(`INSERT OR IGNORE INTO rf_beds(id,room_id,number,code,qr_payload,status,patient_id,updated_at) SELECT id,room_id,number,code,COALESCE(qr_payload,'rehaflow://bed/'||code),status,patient_id,updated_at FROM beds`)}catch{}
 try{await db().q(`INSERT OR IGNORE INTO rf_tasks SELECT * FROM tasks`)}catch{}
 try{await db().q(`INSERT OR IGNORE INTO rf_prescriptions SELECT * FROM prescriptions`)}catch{}
 try{await db().q(`INSERT OR IGNORE INTO rf_documents SELECT * FROM documents`)}catch{}
 try{await db().q(`UPDATE rf_beds SET qr_payload=COALESCE(qr_payload,'rehaflow://bed/'||code),code=COALESCE(code,'BED-'||substr(id,-8))`)}catch{}
}
