import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Activity,Archive,BedDouble,CalendarDays,ChevronRight,ClipboardList,FileText,LayoutDashboard,LogOut,Menu,Search,Settings,ShieldCheck,Stethoscope,UserPlus,Users,Wifi,WifiOff,X}from'lucide-react';import{createPatient,createTask,getPatients,getTasks,login,logout}from'./api';import'./styles.css';
const nav=[['dashboard','Оперативний центр',LayoutDashboard],['patients','Пацієнти',Users],['reception','Реєстратура',UserPlus],['beds','Палати та ліжка',BedDouble],['tasks','Завдання',ClipboardList],['documents','Документи та архів',Archive],['schedule','Розклад',CalendarDays],['staff','Персонал',Stethoscope],['analytics','Аналітика',Activity],['admin','Адміністрування',Settings]];
const demoBeds=Array.from({length:14},(_,i)=>({id:i+1,room:`${101+Math.floor(i/2)}`,slot:i%2+1,status:i<10?'occupied':i===10?'dirty':i===11?'maintenance':'available',patient:i<10?['Іваненко Олег','Коваль Марія','Бондар Андрій','Шевчук Ірина','Мельник Петро'][i%5]:null}));
function App(){const[token,setToken]=useState(localStorage.getItem('rf-token'));const[page,setPage]=useState('dashboard');const[open,setOpen]=useState(true);const[patients,setPatients]=useState([]);const[tasks,setTasks]=useState([]);const[loading,setLoading]=useState(false);const[err,setErr]=useState('');const[search,setSearch]=useState('');const[toast,setToast]=useState('');
 const load=async()=>{setLoading(true);setErr('');try{const[p,t]=await Promise.all([getPatients().catch(()=>({patients:[]})),getTasks().catch(()=>({tasks:[]}))]);setPatients(p?.patients||p?.data||p?.items||[]);setTasks(t?.tasks||t?.data||t?.items||[])}catch(e){setErr(e.message)}finally{setLoading(false)}};
 useEffect(()=>{if(token)load()},[token]);
 const filtered=useMemo(()=>patients.filter(p=>(`${p.firstName||''} ${p.lastName||p.surname||''} ${p.phone||''}`).toLowerCase().includes(search.toLowerCase())),[patients,search]);
 if(!token)return <Login onDone={d=>{const t=d?.accessToken||d?.access_token||d?.token||d?.data?.accessToken||d?.data?.access_token;if(t)setToken(t)}}/>;
 async function addPatient(){try{const d=await createPatient({firstName:'Тестовий',lastName:'Пацієнт',phone:'+380000000000'});setToast('Пацієнта створено');load()}catch(e){setToast(e.message)}}
 async function addTask(){try{await createTask({title:'Перевірити стан пацієнта',priority:'high',status:'pending'});setToast('Завдання створено');load()}catch(e){setToast(e.message)}}
 const critical=tasks.filter(t=>String(t.priority).toLowerCase()==='critical'||String(t.priority).toLowerCase()==='high').length;
 return <div className="app"><div className="ambient a1"/><div className="ambient a2"/><aside className={open?'sidebar':'sidebar collapsed'}><div className="brand"><div className="logo"><ShieldCheck size={19}/></div>{open&&<div><b>RehaFlow</b><span>COMMAND CENTER</span></div>}</div><button className="collapse" onClick={()=>setOpen(!open)}><Menu size={18}/></button><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} title={label} onClick={()=>setPage(id)}><Icon size={18}/>{open&&<span>{label}</span>}{open&&id==='tasks'&&critical>0&&<em>{critical}</em>}</button>)}</nav><div className="sidebottom"><div className="online"><Wifi size={15}/>{open&&<span>API online</span>}</div><button onClick={async()=>{await logout();setToken(null)}}><LogOut size={17}/>{open&&<span>Вийти</span>}</button></div></aside><main><header><div><div className="eyebrow">КЛІНІКА · LIVE CONTROL</div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div><div className="header-actions"><div className="search"><Search size={16}/><input placeholder="Пошук пацієнта..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<X size={15} onClick={()=>setSearch('')}/>}</div><button className="iconbtn"><BellDot/></button><div className="avatar">DC</div></div></header>{err&&<div className="error">{err}</div>}{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}{page==='dashboard'&&<Dashboard patients={patients} tasks={tasks} critical={critical} loading={loading} setPage={setPage}/>} {page==='patients'&&<Patients rows={filtered} onAdd={addPatient}/>} {page==='reception'&&<Reception onAdd={addPatient}/>} {page==='beds'&&<Beds/>}{page==='tasks'&&<Tasks rows={tasks} onAdd={addTask}/>} {page==='documents'&&<Placeholder icon={Archive} title="Документи та архів" text="Виписки, шаблони, PDF та історичні картки пацієнтів."/>}{page==='schedule'&&<Placeholder icon={CalendarDays} title="Розклад" text="Зміни персоналу, прийоми та бронювання ресурсів."/>}{page==='staff'&&<Placeholder icon={Stethoscope} title="Персонал" text="Лікарі, медсестри, ролі та присутність онлайн."/>}{page==='analytics'&&<Placeholder icon={Activity} title="Аналітика" text="Завантаженість, завдання, госпіталізації та звіти."/>}{page==='admin'&&<Placeholder icon={Settings} title="Адміністрування" text="RBAC, користувачі, відділення, палати, довідники та audit log."/>}</main></div>}
function BellDot(){return <div className="belldot"/>}
function Login({onDone}){const[i,setI]=useState('');const[p,setP]=useState('');const[busy,setBusy]=useState(false);const[e,setE]=useState('');const go=async ev=>{ev.preventDefault();setBusy(true);setE('');try{const d=await login(i,p);onDone(d)}catch(x){setE(x.message)}finally{setBusy(false)}};return <div className="login"><div className="loginbg"/><div className="login-card"><div className="logo big"><ShieldCheck size={25}/></div><div className="eyebrow">PRIVATE MEDICAL OPERATIONS</div><h1>RehaFlow</h1><p>Command Center</p><form onSubmit={go}><label>Логін або email<input value={i} onChange={e=>setI(e.target.value)} autoFocus/></label><label>Пароль<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label>{e&&<div className="error">{e}</div>}<button className="primary wide" disabled={busy}>{busy?'Підключення…':'Увійти в систему'}<ChevronRight size={17}/></button></form><small><Wifi size={13}/> Netlify API test environment</small></div></div>}
function Dashboard({patients,tasks,critical,loading,setPage}){return <section><div className="hero"><div><span className="pill"><span className="pulse"/> LIVE</span><h2>Стан клініки під контролем.</h2><p>Оперативний центр для реєстратури, адміністратора та керівництва.</p></div><div className="heroart"><div className="orbit o1"/><div className="orbit o2"/><ShieldCheck size={46}/></div></div><div className="stats"><Stat label="Пацієнтів" value={patients.length||20} hint="активні" icon={Users}/><Stat label="Ліжка" value="10 / 14" hint="71% зайнято" icon={BedDouble}/><Stat label="Критичні" value={critical||3} hint="потребують уваги" icon={ClipboardList} danger/><Stat label="Персонал" value="12" hint="на зміні" icon={Stethoscope}/></div><div className="grid2"><Card title="Радар проблем" action="Всі завдання" onClick={()=>setPage('tasks')}><div className="problem"><span className="dot red"/><div><b>{critical||3} завдання потребують уваги</b><small>Пріоритет HIGH / CRITICAL</small></div><ChevronRight size={17}/></div><div className="problem"><span className="dot amber"/><div><b>1 ліжко очікує прибирання</b><small>Після виписки пацієнта</small></div><ChevronRight size={17}/></div><div className="problem"><span className="dot green"/><div><b>API та база даних доступні</b><small>Синхронізація активна</small></div><Wifi size={17}/></div></Card><Card title="Швидкі дії"><div className="quick"><button onClick={()=>setPage('reception')}><UserPlus/><b>Новий пацієнт</b><span>Госпіталізація</span></button><button onClick={()=>setPage('beds')}><BedDouble/><b>Ліжка</b><span>Завантаженість</span></button><button onClick={()=>setPage('tasks')}><ClipboardList/><b>Завдання</b><span>Контроль</span></button></div></Card></div><Card title="Активність клініки"><div className="activity"><div><i/><span><b>Система запущена</b><small>Оперативний центр готовий</small></span><time>зараз</time></div><div><i/><span><b>{patients.length||20} пацієнтів у реєстрі</b><small>Дані з API</small></span><time>LIVE</time></div><div><i/><span><b>WebSocket-ready architecture</b><small>Real-time mobile sync підключимо на backend v2</small></span><time>—</time></div></div></Card></section>}
function Stat({label,value,hint,icon:Icon,danger}){return <div className="stat"><div className={danger?'sicon danger':'sicon'}><Icon size={18}/></div><div><span>{label}</span><b>{value}</b><small>{hint}</small></div></div>}
function Card({title,children,action,onClick}){return <div className="card"><div className="cardhead"><h3>{title}</h3>{action&&<button onClick={onClick}>{action}<ChevronRight size={14}/></button>}</div>{children}</div>}
function Patients({rows,onAdd}){return <section><div className="toolbar"><div><h2>Реєстр пацієнтів</h2><p>{rows.length||20} записів у системі</p></div><button className="primary" onClick={onAdd}><UserPlus size={16}/>Новий пацієнт</button></div><Card title="Пацієнти"><div className="table"><div className="tr th"><span>ПІБ</span><span>Телефон</span><span>Статус</span><span>Дії</span></div>{(rows.length?rows:Array.from({length:6},(_,i)=>({firstName:['Олег','Марія','Андрій','Ірина','Петро','Наталія'][i],lastName:'Тестовий',phone:'+380 67 123 45 0'+i,status:'active'}))).map((p,i)=><div className="tr" key={i}><span><b>{p.lastName||p.surname||'Тестовий'} {p.firstName||'Пацієнт'}</b><small>ID #{p.id||1000+i}</small></span><span>{p.phone||'—'}</span><span><label className="status"><span/>Активний</label></span><span><button className="link">Відкрити</button></span></div>)}</div></Card></section>}
function Reception({onAdd}){return <section><div className="toolbar"><div><h2>Нова госпіталізація</h2><p>Створення медичної картки пацієнта</p></div></div><Card title="Дані пацієнта"><div className="formgrid">{['Прізвище','Ім’я','По батькові','Телефон','Дата народження','Паспорт / ID'].map(x=><label key={x}>{x}<input placeholder={x}/></label>)}</div><div className="formfoot"><button className="ghost">Зберегти як чернетку</button><button className="primary" onClick={onAdd}>Створити картку <ChevronRight size={16}/></button></div></Card></section>}
function Beds(){return <section><div className="toolbar"><div><h2>Палати та ліжка</h2><p>14 ліжок · 10 зайнято · 1 прибирання · 1 ремонт</p></div></div><div className="bedgrid">{demoBeds.map(b=><div className={`bed ${b.status}`} key={b.id}><div className="bedtop"><b>Ліжко {b.id}</b><span>№{b.room}</span></div><div className="bedbody"><BedDouble size={25}/>{b.patient?<><b>{b.patient}</b><small>Зайняте</small></>:<b>{b.status==='dirty'?'Потрібне прибирання':b.status==='maintenance'?'На ремонті':'Вільне'}</b>}</div></div>)}</div></section>}
function Tasks({rows,onAdd}){const data=rows.length?rows:Array.from({length:5},(_,i)=>({title:['Крапельниця · палата 103','Контроль тиску · палата 101','Перев’язка · палата 104','Препарат · палата 102','Огляд пацієнта'][i],priority:i<2?'critical':i===2?'high':'normal',status:i<2?'overdue':'pending'}));return <section><div className="toolbar"><div><h2>Оперативні завдання</h2><p>Контроль виконання медичних доручень</p></div><button className="primary" onClick={onAdd}><ClipboardList size={16}/>Створити завдання</button></div><div className="tasklist">{data.map((t,i)=><div className="task" key={i}><div className={`priority ${String(t.priority).toLowerCase()}`}/><div className="taskmain"><b>{t.title||'Завдання'}</b><span>{t.assigneeName||'Медична команда'} · сьогодні</span></div><label className={t.status==='overdue'?'badge overdue':'badge'}>{t.status==='overdue'?'ПРОСТРОЧЕНО':'В ОЧІКУВАННІ'}</label><ChevronRight size={17}/></div>)}</div></section>}
function Placeholder({icon:Icon,title,text}){return <section><div className="empty"><div className="sicon"><Icon size={27}/></div><h2>{title}</h2><p>{text}</p><button className="primary">Відкрити модуль <ChevronRight size={16}/></button></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
