import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Archive, Bell, BedDouble, CalendarDays, Check, ChevronRight, ClipboardList, FileText, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, ShieldCheck, Stethoscope, Trash2, UserPlus, Users, Wifi, X } from 'lucide-react';
import { apiFetch, createAppointment, createDocument, createPatient, createTask, createUser, deletePatient, deleteTask, deleteUser, getAppointments, getAudit, getBeds, getDashboard, getDocuments, getPatients, getRoles, getTasks, getUsers, login, logout, updateBed, updatePatient, updateTask, updateUser } from './api';
import './styles.css';

const NAV = [
  ['dashboard', 'Оперативний центр', LayoutDashboard, 'dashboard'],
  ['patients', 'Пацієнти', Users, 'patients'],
  ['reception', 'Реєстратура', UserPlus, 'reception'],
  ['beds', 'Палати та ліжка', BedDouble, 'beds'],
  ['tasks', 'Завдання', ClipboardList, 'tasks'],
  ['documents', 'Документи та архів', Archive, 'documents'],
  ['schedule', 'Розклад', CalendarDays, 'schedule'],
  ['staff', 'Персонал', Stethoscope, 'staff'],
  ['analytics', 'Аналітика', Activity, 'analytics'],
  ['admin', 'Адміністрування', Settings, 'staff'],
];
const roleLabel = { admin: 'Адміністратор', manager: 'Керівник', doctor: 'Лікар', nurse: 'Медсестра', registrar: 'Реєстратура' };

function App() {
  const [token, setToken] = useState(localStorage.getItem('rf-token'));
  const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem('rf-user') || 'null'); } catch { return null; } });
  const [page, setPage] = useState('dashboard');
  const [open, setOpen] = useState(true);
  const [search, setSearch] = useState('');
  const [toast, setToast] = useState('');
  const [error, setError] = useState('');
  const [refresh, setRefresh] = useState(0);
  useEffect(() => { if (toast) { const t = setTimeout(() => setToast(''), 3500); return () => clearTimeout(t); } }, [toast]);
  const doLogout = async () => { await logout(); setToken(null); setUser(null); };
  if (!token) return <Login onDone={d => { setToken(d.accessToken || d.token); setUser(d.user); }} />;
  const canPage = id => { const p = user?.role; if (p === 'admin') return true; const perms = { manager: ['dashboard','patients','reception','beds','tasks','documents','schedule','staff','analytics'], doctor:['dashboard','patients','reception','tasks','documents','schedule'], nurse:['dashboard','patients','tasks','beds','documents'], registrar:['dashboard','patients','reception','schedule'] }; return (perms[p] || []).includes(id); };
  const nav = NAV.filter(x => canPage(x[0]));
  const go = p => { setPage(p); setError(''); };
  const title = nav.find(x => x[0] === page)?.[1] || 'Оперативний центр';
  return <div className="app">
    <div className="ambient a1" /><div className="ambient a2" />
    <aside className={open ? 'sidebar' : 'sidebar collapsed'}>
      <div className="brand"><div className="logo"><ShieldCheck size={19}/></div>{open && <div><b>RehaFlow</b><span>COMMAND CENTER</span></div>}</div>
      <button className="collapse" onClick={() => setOpen(v => !v)}><Menu size={18}/></button>
      <nav>{nav.map(([id,label,Icon]) => <button key={id} className={page===id?'active':''} title={label} onClick={() => go(id)}><Icon size={18}/>{open && <span>{label}</span>}</button>)}</nav>
      <div className="sidebottom"><div className="online"><Wifi size={15}/>{open && <span>API online</span>}</div><div className="who">{open && <><b>{user?.name || 'Користувач'}</b><small>{roleLabel[user?.role] || user?.role}</small></>}</div><button onClick={doLogout}><LogOut size={17}/>{open && <span>Вийти</span>}</button></div>
    </aside>
    <main>
      <header><div><div className="eyebrow">КЛІНІКА · LIVE CONTROL</div><h1>{title}</h1></div><div className="header-actions"><div className="search"><Search size={16}/><input placeholder="Пошук пацієнта..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<X size={15} onClick={()=>setSearch('')}/>}</div><button className="iconbtn"><Bell size={17}/></button><div className="avatar">{(user?.name || 'DC').slice(0,2).toUpperCase()}</div></div></header>
      {error && <div className="error top-error">{error}</div>}
      {toast && <div className="toast" onClick={()=>setToast('')}>{toast}</div>}
      {page==='dashboard' && <Dashboard setPage={go} onError={setError} refresh={refresh} />}
      {page==='patients' && <Patients query={search} setToast={setToast} setError={setError} refresh={refresh} bump={()=>setRefresh(v=>v+1)} />}
      {page==='reception' && <Reception setToast={setToast} setError={setError} bump={()=>setRefresh(v=>v+1)} />}
      {page==='beds' && <Beds setToast={setToast} setError={setError} refresh={refresh} bump={()=>setRefresh(v=>v+1)} />}
      {page==='tasks' && <Tasks setToast={setToast} setError={setError} refresh={refresh} bump={()=>setRefresh(v=>v+1)} />}
      {page==='documents' && <Documents setToast={setToast} setError={setError} refresh={refresh} />}
      {page==='schedule' && <Schedule setToast={setToast} setError={setError} refresh={refresh} />}
      {page==='staff' && <Staff setToast={setToast} setError={setError} role={user?.role} />}
      {page==='analytics' && <Analytics setError={setError} refresh={refresh} />}
      {page==='admin' && <Admin setToast={setToast} setError={setError} />}
    </main>
  </div>;
}

function Login({onDone}){const[i,setI]=useState('mishaborkovskijwork@gmail.com');const[p,setP]=useState('12345678');const[busy,setBusy]=useState(false);const[e,setE]=useState('');const go=async ev=>{ev.preventDefault();setBusy(true);setE('');try{onDone(await login(i,p));}catch(x){setE(x.message)}finally{setBusy(false)}};return <div className="login"><div className="loginbg"/><div className="login-card"><div className="logo big"><ShieldCheck size={25}/></div><div className="eyebrow">PRIVATE MEDICAL OPERATIONS</div><h1>RehaFlow</h1><p>Command Center</p><form onSubmit={go}><label>Логін або email<input value={i} onChange={e=>setI(e.target.value)}/></label><label>Пароль<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label>{e&&<div className="error">{e}</div>}<button className="primary wide" disabled={busy}>{busy?'Підключення…':'Увійти в систему'}<ChevronRight size={17}/></button></form><small><Wifi size={13}/> API + Turso online</small></div></div>}

function Dashboard({setPage,onError,refresh}){const[d,setD]=useState(null);useEffect(()=>{getDashboard().then(setD).catch(e=>onError(e.message))},[refresh]);const s=d?.stats||{};return <section><div className="hero"><div><span className="pill"><span className="pulse"/> LIVE</span><h2>Стан клініки під контролем.</h2><p>Єдиний оперативний центр для реєстратури, лікарів, медсестер та керівництва.</p></div><div className="heroart"><div className="orbit o1"/><div className="orbit o2"/><ShieldCheck size={46}/></div></div><div className="stats"><Stat label="Пацієнтів" value={s.patients??'—'} hint="активні" icon={Users}/><Stat label="Ліжка" value={`${s.occupiedBeds??0} / ${(s.occupiedBeds??0)+(s.availableBeds??0)}`} hint="зайнято / доступно" icon={BedDouble}/><Stat label="Відкриті завдання" value={s.openTasks??'—'} hint="під контролем" icon={ClipboardList} danger/><Stat label="Персонал" value={s.staffOnline??'—'} hint="активні акаунти" icon={Stethoscope}/></div><div className="grid2"><Card title="Швидкі дії"><div className="quick"><button onClick={()=>setPage('reception')}><UserPlus/><b>Новий пацієнт</b><span>Госпіталізація</span></button><button onClick={()=>setPage('beds')}><BedDouble/><b>Ліжка</b><span>Статуси</span></button><button onClick={()=>setPage('tasks')}><ClipboardList/><b>Завдання</b><span>Команда</span></button></div></Card><Card title="Система"><div className="activity"><div><i className="green-dot"/><span><b>API доступний</b><small>Netlify Functions</small></span><time>LIVE</time></div><div><i className="green-dot"/><span><b>База даних</b><small>Turso / libSQL</small></span><time>LIVE</time></div><div><i className="green-dot"/><span><b>Авторизація</b><small>RBAC + sessions</small></span><time>OK</time></div></div></Card></div></section>}
function Stat({label,value,hint,icon:Icon,danger}){return <div className="stat"><div className={danger?'sicon danger':'sicon'}><Icon size={18}/></div><div><span>{label}</span><b>{value}</b><small>{hint}</small></div></div>}
function Card({title,children,action,onClick}){return <div className="card"><div className="cardhead"><h3>{title}</h3>{action&&<button onClick={onClick}>{action}<ChevronRight size={14}/></button>}</div>{children}</div>}

function Patients({query,setToast,setError,refresh,bump}){const[rows,setRows]=useState([]);const[edit,setEdit]=useState(null);const load=()=>getPatients(query).then(d=>setRows(d?.patients||[])).catch(e=>setError(e.message));useEffect(()=>{load()},[query,refresh]);const save=async p=>{try{if(p.id){await updatePatient(p.id,p)}else await createPatient(p);setToast('Пацієнта збережено');setEdit(null);bump();}catch(e){setError(e.message)}};return <section><Toolbar title="Реєстр пацієнтів" text={`${rows.length} записів`} action={<button className="primary" onClick={()=>setEdit({firstName:'',lastName:'',middleName:'',phone:'',birthDate:'',diagnosis:'',room:'',bed:''})}><Plus size={16}/>Новий пацієнт</button>}/><Card title="Пацієнти"><div className="table"><div className="tr th"><span>ПІБ</span><span>Телефон</span><span>Діагноз</span><span>Статус</span><span/></div>{rows.map(p=><div className="tr" key={p.id}><span><b>{p.last_name} {p.first_name}</b><small>{p.birth_date||'Дата не вказана'} · ID {p.id.slice(0,10)}</small></span><span>{p.phone||'—'}</span><span>{p.diagnosis||'—'}</span><span><label className="status"><span/> {p.status==='active'?'Активний':p.status}</label></span><span className="row-actions"><button className="link" onClick={()=>setEdit({id:p.id,firstName:p.first_name,lastName:p.last_name,middleName:p.middle_name||'',phone:p.phone||'',birthDate:p.birth_date||'',diagnosis:p.diagnosis||'',room:p.room||'',bed:p.bed||''})}>Редагувати</button><button className="danger-btn" onClick={async()=>{if(confirm('Видалити пацієнта?')){try{await deletePatient(p.id);setToast('Пацієнта видалено');bump()}catch(e){setError(e.message)}}}}><Trash2 size={15}/></button></span></div>)}</div></Card>{edit&&<PatientModal value={edit} onClose={()=>setEdit(null)} onSave={save}/>}</section>}
function PatientModal({value,onClose,onSave}){const[v,setV]=useState(value);return <Modal title={v.id?'Редагувати пацієнта':'Новий пацієнт'} onClose={onClose}><div className="formgrid">{[['lastName','Прізвище'],['firstName','Ім’я'],['middleName','По батькові'],['phone','Телефон'],['birthDate','Дата народження'],['diagnosis','Діагноз'],['room','Палата'],['bed','Ліжко']].map(([k,l])=><label key={k}>{l}<input value={v[k]||''} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}</div><div className="formfoot"><button className="ghost" onClick={onClose}>Скасувати</button><button className="primary" onClick={()=>onSave(v)}><Check size={16}/>Зберегти</button></div></Modal>}

function Reception({setToast,setError,bump}){const[v,setV]=useState({lastName:'',firstName:'',middleName:'',phone:'',birthDate:'',diagnosis:'',room:'',bed:''});const save=async()=>{try{await createPatient(v);setToast('Картку пацієнта створено');setV({lastName:'',firstName:'',middleName:'',phone:'',birthDate:'',diagnosis:'',room:'',bed:''});bump()}catch(e){setError(e.message)}};return <section><Toolbar title="Реєстратура" text="Госпіталізація та нова медична картка"/><Card title="Нова госпіталізація"><div className="formgrid">{[['lastName','Прізвище'],['firstName','Ім’я'],['middleName','По батькові'],['phone','Телефон'],['birthDate','Дата народження'],['diagnosis','Попередній діагноз'],['room','Палата'],['bed','Ліжко']].map(([k,l])=><label key={k}>{l}<input value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}</div><div className="formfoot"><button className="ghost">Зберегти чернетку</button><button className="primary" onClick={save}>Створити картку <ChevronRight size={16}/></button></div></Card></section>}

function Beds({setToast,setError,refresh,bump}){const[rows,setRows]=useState([]);useEffect(()=>{getBeds().then(d=>setRows(d.beds||[])).catch(e=>setError(e.message))},[refresh]);const upd=async(b,status)=>{try{await updateBed(b.id,{status,patientId:b.patient_id});setToast('Статус ліжка оновлено');bump()}catch(e){setError(e.message)}};return <section><Toolbar title="Палати та ліжка" text="Завантаженість та санітарні статуси"/><div className="bedgrid">{rows.map(b=><div className={`bed ${b.status}`} key={b.id}><div className="bedtop"><b>Ліжко {b.bed_number}</b><span>№{b.room}</span></div><div className="bedbody"><BedDouble size={25}/><b>{b.patient_name||({'available':'Вільне','dirty':'Потрібне прибирання','maintenance':'На ремонті'}[b.status]||'Зайняте')}</b><small>{b.status}</small></div><select value={b.status} onChange={e=>upd(b,e.target.value)}><option value="available">Вільне</option><option value="occupied">Зайняте</option><option value="dirty">Прибирання</option><option value="maintenance">Ремонт</option></select></div>)}</div></section>}

function Tasks({setToast,setError,refresh,bump}){const[rows,setRows]=useState([]);const[users,setUsers]=useState([]);const[patients,setPatients]=useState([]);const[newTask,setNewTask]=useState(null);const load=()=>Promise.all([getTasks(),getUsers().catch(()=>({users:[]})),getPatients()]).then(([t,u,p])=>{setRows(t.tasks||[]);setUsers(u.users||[]);setPatients(p.patients||[])}).catch(e=>setError(e.message));useEffect(()=>{load()},[refresh]);const save=async v=>{try{if(v.id)await updateTask(v.id,v);else await createTask(v);setToast('Завдання збережено');setNewTask(null);bump()}catch(e){setError(e.message)}};return <section><Toolbar title="Оперативні завдання" text={`${rows.length} завдань`} action={<button className="primary" onClick={()=>setNewTask({title:'',description:'',patientId:'',assignedTo:'',priority:'normal',status:'pending',dueAt:''})}><Plus size={16}/>Створити</button>}/><Card title="Черга виконання"><div className="tasklist">{rows.map(t=><div className="task" key={t.id}><div className={`priority ${t.priority}`}/><div className="taskmain"><b>{t.title}</b><span>{t.patient_name||'Без пацієнта'} · {t.assignee_name||'Не призначено'}</span></div><label className={`badge ${t.status}`}>{t.status}</label><div className="row-actions"><select value={t.status} onChange={async e=>{try{await updateTask(t.id,{status:e.target.value});bump()}catch(x){setError(x.message)}}}><option value="pending">Очікує</option><option value="in_progress">В роботі</option><option value="done">Виконано</option><option value="overdue">Прострочено</option></select><button className="link" onClick={()=>setNewTask({id:t.id,title:t.title,description:t.description||'',patientId:t.patient_id||'',assignedTo:t.assigned_to||'',priority:t.priority,status:t.status,dueAt:t.due_at||''})}>Редагувати</button><button className="danger-btn" onClick={async()=>{if(confirm('Видалити завдання?')){await deleteTask(t.id);setToast('Завдання видалено');bump()}}}><Trash2 size={15}/></button></div></div>)}</div></Card>{newTask&&<TaskModal value={newTask} users={users} patients={patients} onClose={()=>setNewTask(null)} onSave={save}/>}</section>}
function TaskModal({value,users,patients,onClose,onSave}){const[v,setV]=useState(value);return <Modal title={v.id?'Редагувати завдання':'Нове завдання'} onClose={onClose}><div className="formgrid">{<label>Назва<input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label>}<label>Опис<input value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label><label>Пацієнт<select value={v.patientId} onChange={e=>setV({...v,patientId:e.target.value})}><option value="">Без пацієнта</option>{patients.map(p=><option key={p.id} value={p.id}>{p.last_name} {p.first_name}</option>)}</select></label><label>Виконавець<select value={v.assignedTo} onChange={e=>setV({...v,assignedTo:e.target.value})}><option value="">Не призначено</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select></label><label>Пріоритет<select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Термін<input type="datetime-local" value={v.dueAt?String(v.dueAt).slice(0,16):''} onChange={e=>setV({...v,dueAt:e.target.value})}/></label></div><div className="formfoot"><button className="ghost" onClick={onClose}>Скасувати</button><button className="primary" onClick={()=>onSave(v)}>Зберегти</button></div></Modal>}

function Documents({setToast,setError,refresh}){const[rows,setRows]=useState([]);const[patients,setPatients]=useState([]);const[v,setV]=useState({title:'',category:'discharge',patientId:'',fileName:'',fileUrl:''});const load=()=>Promise.all([getDocuments(),getPatients()]).then(([d,p])=>{setRows(d.documents||[]);setPatients(p.patients||[])}).catch(e=>setError(e.message));useEffect(()=>load(),[refresh]);const save=async()=>{try{await createDocument(v);setToast('Документ додано');setV({title:'',category:'discharge',patientId:'',fileName:'',fileUrl:''});load()}catch(e){setError(e.message)}};return <section><Toolbar title="Документи та архів" text="Медичні документи, виписки та історія"/><div className="grid2"><Card title="Додати документ"><div className="formgrid"><label>Назва<input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label><label>Категорія<select value={v.category} onChange={e=>setV({...v,category:e.target.value})}><option value="discharge">Виписка</option><option value="analysis">Аналіз</option><option value="ecg">ЕКГ</option><option value="consent">Згода</option><option value="other">Інше</option></select></label><label>Пацієнт<select value={v.patientId} onChange={e=>setV({...v,patientId:e.target.value})}><option value="">Не прив'язано</option>{patients.map(p=><option key={p.id} value={p.id}>{p.last_name} {p.first_name}</option>)}</select></label><label>Файл<input value={v.fileName} placeholder="report.pdf" onChange={e=>setV({...v,fileName:e.target.value})}/></label><label>URL<input value={v.fileUrl} onChange={e=>setV({...v,fileUrl:e.target.value})}/></label></div><button className="primary" onClick={save}>Додати документ</button></Card><Card title="Останні документи"><div className="table compact">{rows.slice(0,8).map(d=><div className="tr" key={d.id}><span><b>{d.title}</b><small>{d.patient_name||'Без пацієнта'}</small></span><span>{d.category}</span><span>{d.file_name||'—'}</span></div>)}</div></Card></div></section>}

function Schedule({setToast,setError,refresh}){const[rows,setRows]=useState([]);const[patients,setPatients]=useState([]);const[users,setUsers]=useState([]);const[v,setV]=useState({startsAt:'',patientId:'',doctorId:'',type:'consultation',durationMinutes:30,notes:''});const load=()=>Promise.all([getAppointments(),getPatients(),getUsers().catch(()=>({users:[]}))]).then(([a,p,u])=>{setRows(a.appointments||[]);setPatients(p.patients||[]);setUsers(u.users||[])}).catch(e=>setError(e.message));useEffect(()=>load(),[refresh]);const save=async()=>{try{await createAppointment(v);setToast('Прийом заплановано');setV({...v,startsAt:'',patientId:'',notes:''});load()}catch(e){setError(e.message)}};return <section><Toolbar title="Розклад" text="Прийоми та бронювання часу"/><div className="grid2"><Card title="Новий прийом"><div className="formgrid"><label>Дата і час<input type="datetime-local" value={v.startsAt} onChange={e=>setV({...v,startsAt:e.target.value})}/></label><label>Пацієнт<select value={v.patientId} onChange={e=>setV({...v,patientId:e.target.value})}><option value="">Обрати</option>{patients.map(p=><option key={p.id} value={p.id}>{p.last_name} {p.first_name}</option>)}</select></label><label>Лікар<select value={v.doctorId} onChange={e=>setV({...v,doctorId:e.target.value})}><option value="">Автоматично</option>{users.filter(u=>['doctor','admin','manager'].includes(u.role)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Тип<select value={v.type} onChange={e=>setV({...v,type:e.target.value})}><option value="consultation">Консультація</option><option value="procedure">Процедура</option><option value="followup">Контроль</option></select></label><label>Примітка<input value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label></div><button className="primary" onClick={save}>Запланувати</button></Card><Card title="Найближчі прийоми"><div className="table compact">{rows.slice(0,10).map(a=><div className="tr" key={a.id}><span><b>{a.patient_name||'Без пацієнта'}</b><small>{a.doctor_name||'Команда'}</small></span><span>{String(a.starts_at).replace('T',' ').slice(0,16)}</span><span>{a.type}</span><span className="badge">{a.status}</span></div>)}</div></Card></div></section>}

function Staff({setToast,setError,role}){const[rows,setRows]=useState([]);const[newUser,setNewUser]=useState(null);const load=()=>getUsers().then(d=>setRows(d.users||[])).catch(e=>setError(e.message));useEffect(()=>load(),[]);if(!['admin','manager'].includes(role))return <Empty title="Персонал" text="У вашій ролі доступ обмежений до профілів персоналу."/>;const save=async v=>{try{if(v.id)await updateUser(v.id,v);else await createUser(v);setToast('Користувача збережено');setNewUser(null);load()}catch(e){setError(e.message)}};return <section><Toolbar title="Персонал" text={`${rows.length} облікових записів`} action={role==='admin'?<button className="primary" onClick={()=>setNewUser({name:'',email:'',password:'',role:'doctor',active:true})}><Plus size={16}/>Новий користувач</button>:null}/><Card title="Користувачі"><div className="table"><div className="tr th"><span>Користувач</span><span>Роль</span><span>Статус</span><span/></div>{rows.map(u=><div className="tr" key={u.id}><span><b>{u.name}</b><small>{u.email}</small></span><span><label className="role-pill">{roleLabel[u.role]||u.role}</label></span><span>{u.active?'Активний':'Вимкнено'}</span><span className="row-actions"><button className="link" onClick={()=>setNewUser({id:u.id,name:u.name,email:u.email,password:'',role:u.role,active:!!u.active})}>Редагувати</button>{role==='admin'&&u.id!=='admin-default'&&<button className="danger-btn" onClick={async()=>{if(confirm('Видалити користувача?')){await deleteUser(u.id);load()}}}><Trash2 size={15}/></button>}</span></div>)}</div></Card>{newUser&&<UserModal value={newUser} onClose={()=>setNewUser(null)} onSave={save}/>}</section>}
function UserModal({value,onClose,onSave}){const[v,setV]=useState(value);return <Modal title={v.id?'Редагувати користувача':'Новий користувач'} onClose={onClose}><div className="formgrid"><label>Ім’я<input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Email<input value={v.email} onChange={e=>setV({...v,email:e.target.value})}/></label><label>Пароль<input type="password" value={v.password} onChange={e=>setV({...v,password:e.target.value})} placeholder={v.id?'Не змінювати':''}/></label><label>Роль<select value={v.role} onChange={e=>setV({...v,role:e.target.value})}><option value="doctor">Лікар</option><option value="nurse">Медсестра</option><option value="registrar">Реєстратура</option><option value="manager">Керівник</option><option value="admin">Адміністратор</option></select></label><label className="check"><input type="checkbox" checked={v.active} onChange={e=>setV({...v,active:e.target.checked})}/> Активний</label></div><div className="formfoot"><button className="ghost" onClick={onClose}>Скасувати</button><button className="primary" onClick={()=>onSave(v)}>Зберегти</button></div></Modal>}

function Analytics({setError,refresh}){const[d,setD]=useState(null);const[a,setA]=useState([]);useEffect(()=>{Promise.all([getDashboard(),getAudit().catch(()=>({audit:[]}))]).then(([x,y])=>{setD(x?.stats);setA(y?.audit||[])}).catch(e=>setError(e.message))},[refresh]);return <section><Toolbar title="Аналітика" text="Оперативні показники та аудит"/><div className="stats"><Stat label="Пацієнти" value={d?.patients??'—'} hint="активні" icon={Users}/><Stat label="Ліжка" value={d?.occupiedBeds??'—'} hint="зайняті" icon={BedDouble}/><Stat label="Завдання" value={d?.openTasks??'—'} hint="відкриті" icon={ClipboardList}/><Stat label="Персонал" value={d?.staffOnline??'—'} hint="активні" icon={Stethoscope}/></div><Card title="Останні події аудиту"><div className="table compact">{a.slice(0,12).map(x=><div className="tr" key={x.id}><span><b>{x.action} · {x.entity}</b><small>{x.user_name||'System'} · {x.entity_id}</small></span><span>{String(x.created_at).replace('T',' ').slice(0,19)}</span></div>)}</div></Card></section>}

function Admin({setToast,setError}){const[roles,setRoles]=useState([]);useEffect(()=>{getRoles().then(d=>setRoles(d.roles||[])).catch(e=>setError(e.message))},[]);return <section><Toolbar title="Адміністрування" text="RBAC, ролі, дозволи та контроль системи"/><div className="grid2"><Card title="Ролі та дозволи"><div className="roles">{roles.map(r=><div className="role-card" key={r.role}><b>{roleLabel[r.role]||r.role}</b><small>{r.permissions.join(', ')}</small></div>)}</div></Card><Card title="Безпека"><div className="activity"><div><i className="green-dot"/><span><b>RBAC активний</b><small>Доступ залежить від ролі</small></span><time>OK</time></div><div><i className="green-dot"/><span><b>Сесії</b><small>12 годин дії access token</small></span><time>OK</time></div><div><i className="green-dot"/><span><b>Audit log</b><small>CRUD та адміністративні дії</small></span><time>ON</time></div></div></Card></div></section>}

function Toolbar({title,text,action}){return <div className="toolbar"><div><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Empty({title,text}){return <section><Toolbar title={title} text="Модуль"/><Card title={title}><div className="empty"><FileText size={30}/><b>{text}</b></div></Card></section>}
function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><div className="modalhead"><h3>{title}</h3><button onClick={onClose}><X size={18}/></button></div>{children}</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
